name: TVHeadend
version: 1e059e8
stage: experimental
slug: tvheadend
description: TV streaming server and recorder.
url: https://github.com/afedchin/addon-tvheadend
init: false
arch:
- aarch64
- amd64
- armhf
- armv7
- i386
webui: http://[HOST]:[PORT:9981]/
devices:
- /dev/dvb
- /dev/dri
ports:
  9981/tcp: 9981
  9982/tcp: 9982
  8888/tcp: 8888
  5004/tcp: 5004
ports_description:
  9981/tcp: TVH Web Interface
  9982/tcp: TVH HTSP
  8888/tcp: OSCam Web Interface
  5004/tcp: tvhProxy
map:
- homeassistant_config:rw
- media:rw
options:
  TVH_URL: http://192.168.100.93:9981
  TVH_BINDADDR: 0.0.0.0
  TVH_PROXY_HOST: '[HOST]'
  TVH_PROXY_PORT: 5004
  TVH_TUNER_COUNT: 2
  TVH_WEIGHT: 300
  TVH_CHUNK_SIZE: 1048576
  TVH_PROFILE: pass
schema:
  TVH_URL: str
  TVH_BINDADDR: str
  TVH_PROXY_HOST: str
  TVH_PROXY_PORT: int
  TVH_TUNER_COUNT: int
  TVH_WEIGHT: int?
  TVH_CHUNK_SIZE: int?
  TVH_PROFILE: str?
host_network: true
image: ghcr.io/afedchin/tvheadend/{arch}
